Charles (#29)
* Added README.md

* add .gitignore

* new changes

* login css styling

* update urls

* forms.py

* forms.py

* forms

* forms

* update navbar

* style: menu item

* style: menu item

* style: hightlight selected menu

* chore: content structure

* chore: content structure

* add: monitor select box

* refactor: html structure

* refactor: html structure

* refactor: html structure

* gitignore: add .DS_Store files

* change session age to 3600

* add: renu favicon

* delete .DS_Store

* deleted sqlitte

* chore: remove unsed packages

* feat: download site files

* Debug: false

* add scheduler package

* change to hours for sites download

* gitignore: Exception

* Hide secret key

* fix conflict

* set ALLOWED HOSTS

* Github Actions

* update github actions

* test

* test

* changed check debug settngs

* Test Actions

* changes

* changes

* changes

* changes

* changes

* updated settings

* updated settings

* Testing Actions when debug is left true

* Testing Actions when debug is left true

* updated settings

* Testing Actions when debug is left true

* check Debug in Settings

* Testing Actions when debug is left true

* Actions environment variables

* Testing Actions when debug is left true

* Actions environment variables

diff --git a/.github/workflows/debug_check.yml b/.github/workflows/debug_check.yml
--- a/.github/workflows/debug_check.yml
+++ b/.github/workflows/debug_check.yml
@@ -26,3 +26,12 @@ jobs:
 
       - name: Run Debug Check
         run: python check_debug_setting.py
+
+      - name: Check Debug Script Result
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "Debug check passed. Proceeding with merging the pull request."
+          else
+            echo "ERROR: Debug check failed. The pull request cannot be merged."
+            exit 1
+          fi
